// Models
export 'models/route_model.dart';
export 'models/ticket_model.dart';
export 'models/driver_model.dart';
export 'models/vehicle_model.dart';
export 'models/chat_model.dart';

// Services
export 'services/auth_service.dart';
export 'services/route_service.dart';
export 'services/ticket_service.dart';
export 'services/chat_service.dart';

// Providers
export 'providers/user_provider.dart';
export 'providers/route_provider.dart';
export 'providers/ticket_provider.dart';
export 'providers/chat_provider.dart';
export 'providers/navigation_provider.dart';

// Colors
export 'colors/app_colors.dart';

// Routes
export 'routes/app_routes.dart';

// Widgets
export 'widgets/app_header.dart';
export 'widgets/app_text_field.dart';
export 'widgets/app_logo.dart';
export 'widgets/success_modal.dart';
export 'widgets/confirmation_button.dart';
export 'widgets/navbar.dart';
export 'widgets/trip_card.dart';
export 'widgets/passage_card.dart';
export 'widgets/chat_card.dart';
export 'widgets/filter.dart';
export 'widgets/app_card.dart';
export 'widgets/menu_item.dart';
export 'widgets/menu_profile_header.dart';
export 'widgets/auth_tabs.dart';
export 'widgets/tab_selector.dart';
export 'widgets/driver_info_card.dart';
export 'widgets/support_contact_card.dart';
export 'widgets/rating_tags_section.dart';
export 'widgets/payment_summary.dart';
export 'widgets/wallet_balance.dart';
export 'widgets/chat_bubble.dart';
export 'widgets/profile_header.dart';
export 'widgets/star_rating.dart';
export 'widgets/screen_app_bar.dart';
export 'widgets/trip_info_card.dart';
export 'widgets/qr_code_section.dart';
export 'widgets/pix_key_section.dart';
export 'widgets/receipt_header.dart';

// Screens
export 'screens/login.dart';
export 'screens/register.dart';
export 'screens/forgot_password.dart';
export 'screens/home_page.dart';
export 'screens/search.dart';
export 'screens/results.dart';
export 'screens/tickets.dart';
export 'screens/chat.dart';
export 'screens/menu.dart';
export 'screens/profile.dart';
export 'screens/profile_edit.dart';
export 'screens/passage_details.dart';
export 'screens/payment.dart';
export 'screens/receipt.dart';
export 'screens/rating.dart';
export 'screens/private_chat.dart';
export 'screens/add_card.dart';
export 'screens/add_pix.dart';
